
version: '3'
services:
  app:
    build: .
    container_name: gtfsauvasa
    image: gtfsauvasa:latest
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    environment:
      NODE_ENV: production
