version: "3.9"
services:
  gtfsauvasa:
    build: .
    container_name: gtfsauvasa
    image: gtfsauvasa:latest
    ports:
      - 3333:3333
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3333